# Generated by Django 3.2.8 on 2021-10-08 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAlbum', '0002_auto_20211008_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_name', models.CharField(max_length=100)),
                ('image_details', models.TextField()),
                ('image_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAlbum.category')),
                ('image_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myAlbum.location')),
            ],
        ),
    ]
