# Generated by Django 3.2.8 on 2021-10-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAlbum', '0004_rename_image_category_image_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_location',
            new_name='location',
        ),
    ]
